export interface Property {
  _id?: Number,
  wholesaler_id: String,
  address: String,
  city: String,
  state: String,
  zipCode: String,
  purchasePrice: String,
  bedrooms: Number,
  bathrooms: Number,
  rehabCostMin: String,
  rehabCostMax: String,
  afterRepairValue: String,
  capRate: String,
  averageRent: String,
  squareFootage: String,
  propertyType: String,
  yearBuilt: String,
  status: String,
  comps: Array<Object>,
  photos: Array<String>,
  property?: any,
  data?: any
}